### ISSUE TITLE
Return 2 values

### ISSUE THREAD

**Issue by marcos44pl** [emcezet/sv-tools#10]
Python handles multiply returns that tuple is not needed (look more pretty, but indeed it is  handled by tuple)
https://github.com/emcezet/sv-tools/blob/de4e195a661e0625ba3435f8fb87df4cb5ea9b70/SVEngine/SVUtils.py#L78

**Comment by emcezet** [comment]
Will do, project moved in different direction, so this line will not be fixed, thanks!
