### ISSUE TITLE
Get familiar with framework unittest

### ISSUE THREAD

**Issue by marcos44pl** [emcezet/sv-tools#4]
Great framework if you want to write real UTs: https://docs.python.org/2/library/unittest.html
These tests are not very 'unit'.

https://github.com/emcezet/sv-tools/blob/753dc702e4228d050b3d1df9a406a2f687463a7e/SVEngine/tests/ut_SVParser.py#L31

**Comment by emcezet** [comment]
Started using unittests. More will follow :)
