### ISSUE TITLE
unittest framework!

### ISSUE THREAD

**Issue by marcos44pl** [emcezet/sv-tools#5]
don't do it.  It is very risky to change path in whole module. It is very depended from flow and module import order.  
unittest framework changes path globally - better to use it!
or you can use from ..SVParser import SVParser but it is nasty in UTs (what if you change tests location)...

https://github.com/emcezet/sv-tools/blob/753dc702e4228d050b3d1df9a406a2f687463a7e/SVEngine/tests/ut_SVInterface.py#L24

**Comment by emcezet** [comment]
Started using unittests. More will follow :)
