### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by marcos44pl** [emcezet/sv-tools#7]
why python 2.7? Python 2 is going to loose support. It is recommended to start new project in python 3

https://github.com/emcezet/sv-tools/blob/753dc702e4228d050b3d1df9a406a2f687463a7e/SVEngine/SVInterface.py#L23

**Comment by emcezet** [comment]
I had in mind that this project may be used on legacy architectures at PG; after consideration I will move to python 3.
